### ISSUE TITLE
seperate vs separate

### ISSUE THREAD

**Issue by knightsamar** [osuosl-cookbooks/osl-openstack#80]
We have an attribute `seperate_network_node` but default recipe refers to `separate_network_node`.

This hasn't broken anything yet, but we must choose to side with the British or American, lest we have our own Mars Orbiter mishap(http://www.cnn.com/TECH/space/9909/30/mars.metric.02/)

**Comment by fahlmant** [comment]
https://thechive.files.wordpress.com/2015/06/god-bless-merica-happy-fourth-4th-july-0-e1435697096476.jpg?quality=85&strip=info&w=600&h=403&crop=1

**Comment by fahlmant** [comment]
![god-bless-merica-happy-fourth-4th-july-0-e1435697096476](https://cloud.githubusercontent.com/assets/8716749/25976074/464a8c34-3667-11e7-9eac-9b76219b0e77.jpg)

**Comment by knightsamar** [comment]
Is that Chuck Norris ?

**Comment by ramereth** [comment]
Derp, did I really do that?
