### ISSUE TITLE
Networking isn't set up automatically

### ISSUE THREAD

**Issue by doublej472** [osuosl-cookbooks/osl-openstack#83]
I had to set up networking manually on the mitaka openstack controller, `oprod-controller1.osuosl.org`, such as dns nameservers and firewall rules. You can see what I did in this [trello card](https://trello.com/c/tyAUw5Pv/406-mitaka-test-kitchen-verification). This should be handled by this cookbook.

**Comment by ramereth** [comment]
Most of this are difficult to do using the upstream cookbooks and currently outside the scope of this cookbook.

**Comment by doublej472** [comment]
Should this be included in the readme then? There really isn't anything there for setting up networking

**Comment by ramereth** [comment]
It's currently documented on our internal docs and that's where it should be. It might need updating.
